# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bE0V5r5NjL5Br9QI7TKzFcR5N9AK-MU
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

import joblib

# =========================
# 1. LOAD DATA
# =========================
df = pd.read_csv("sonar_acoustic_dataset.csv")

# =========================
# 2. TARGET FIX (IMPORTANT)
# =========================
X = df.drop("Sound Source", axis=1)
y = df["Sound Source"]

# Convert bool → int (cleaner for models)
X = X.astype(float)

# =========================
# 3. TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# =========================
# 4. MODEL (OPTIMIZED)
# =========================
model = ExtraTreesClassifier(
    n_estimators=500,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features='sqrt',
    random_state=42,
    n_jobs=-1
)

# =========================
# 5. TRAIN
# =========================
model.fit(X_train, y_train)

# =========================
# 6. PREDICT
# =========================
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)

# =========================
# 7. METRICS
# =========================
accuracy  = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average="weighted")
recall    = recall_score(y_test, y_pred, average="weighted")
f1        = f1_score(y_test, y_pred, average="weighted")
auc       = roc_auc_score(y_test, y_proba, multi_class='ovr')

# =========================
# 8. PRINT CLEAN OUTPUT
# =========================
print({
    "model": "ExtraTrees",
    "accuracy": round(accuracy, 6),
    "precision": round(precision, 6),
    "recall": round(recall, 6),
    "f1": round(f1, 6),
    "auc": round(auc, 6)
})

# =========================
# 9. SAVE MODEL
# =========================
joblib.dump(model, "best_model.pkl")

